export const RoutingConstants = {
  SYSTEM: 'sys',
  HOME: 'home',
  NEWS_HUB: 'news-hub',
  NEWS: 'news',
  WRAPUPS: 'wrap-ups',
  ARTICLES: 'articles',
  TECH_HUB: 'tech-hub',
  MARKET_HUB: 'market-hub',
  LIVE_TRADING_ROOM: 'live-trading-room',
  CALENDER: 'Calender',
  EDUCATION: 'education',
  OPTINIONS_HUB: 'opinions-hub',
  MEDIA_HUB: 'media-hub',
  PUBLICATIONS: 'publications',
  LEGAL: 'legal',
  VIDEOS: 'videos',
  PRODUCTS: 'products',
  WEBINAR: 'webinar',
  SEMINAR: 'seminar',
  SMART_REPORTS: 'smart-reports',
  TECHNICAL_REPORTS: 'technical-reports',
  CALCULATORS: 'calculators',
  ECONOMIC_CALENDAR: 'economic-calendar',
  HOLYDAY_CALENDAR: 'holyday-calendar',
  CENTRAL_BANKS_CALENDAR: 'central-banks-calendar'

};
